create table "resource_object_entity"
(
    "id"    integer not null,
    "path"  varchar(255),
    "resource_value" varchar(255),
    primary key ("id")
);

create table "user_entity"
(
    "id"       integer generated by default as identity,
    "name"     varchar(255) unique,
    "password" varchar(255),
    "roles"    varchar(255),
    primary key ("id")
);